### ISSUE TITLE
I am not able to see the positions of esp32 on the map , i have typed the credentials at config.js , but still the devices are not showing

### ISSUE THREAD

**Issue by sourabhmisal** [jarkko-hautakorpi/iBeacon-indoor-positioning-demo#10]

**Comment by simonbogh** [comment]
I believe this is related to #5. I am in the same situation that the stations are not showing up in the map. Another issue that may be related is that if a station finds more than one or many beacons, then it will not publish to the MQTT broker.

**Comment by simonbogh** [comment]
@jarkko-hautakorpi is it true that stations will not show on the map until there are three connected? I just connected three stations, and now they show up on the map.
