### ISSUE TITLE
geofence 

### ISSUE THREAD

**Issue by RogierQ** [jarkko-hautakorpi/iBeacon-indoor-positioning-demo#11]
First of all thanks for sharing your project / knowledge!!

Is it possible to send out actions when a tag is in a room or circle for example?
Something over mqtt would be perfect to me.

**Comment by jarkko-hautakorpi** [comment]
Position is published to MQTT already, so one could use that in the server for example to generate new message to other topic. This demo app just publishes the, not so accurate position when 3 stations see the beacon.
