### ISSUE TITLE
Trilateration Concept in BLE Indoor Positioning System

### ISSUE THREAD

**Issue by Mahamutha** [jarkko-hautakorpi/iBeacon-indoor-positioning-demo#13]
Hi,

Consider I have three BLE gateways/stations which receives the RSSI value from the BLE Tag/Beacon. The BLE tag would have sent RSSI value to all the three gateways say for ex,

> BLE Tag1 to Gateway1 = -45
> BLE Tag1 to Gateway2 = -56
> BLE Tag1 to Gateway3 = -61

I have coordinate for all the three gateways like,

> Gateway1 = 10,10
> Gateway2 = 100,10
> Gateway3 = 10,100

Now How to convert the RSSI values as distance in order to proceed with the trilateration technique?

**Comment by jarkko-hautakorpi** [comment]
Here https://github.com/jarkko-hautakorpi/iBeacon-indoor-positioning-demo/blob/10a22d9427e63cdf199e63d87789e0770ee3ac6c/dashboard/src/Positioner/PositionCalculator.js#L15

And please see the Trilat -library for position calculation in X,Y coordinates https://www.npmjs.com/package/trilat
