### ISSUE TITLE
ESP32 loses connection with the Wifi

### ISSUE THREAD

**Issue by jcrc1962** [jarkko-hautakorpi/iBeacon-indoor-positioning-demo#16]
Hello, I installed the code in some ESP32 modules, it works well monitoring the ibeacons and reporting all found beacons to MQTT topic, my problem is that after a few hours working, the ESP32 loses connection with the Wifi and is not able to reconnect until I do a reboot. I will appreciate any help

**Comment by jarkko-hautakorpi** [comment]
Try keep the ESP32 in a seria port, add some more debug messages and see what happens, maybe a memory leak and a crash happens or something..
Please do a pull request if you find a bug.
