### ISSUE TITLE
Dashboad not working

### ISSUE THREAD

**Issue by umaaraziz** [jarkko-hautakorpi/iBeacon-indoor-positioning-demo#2]
Hello Hautakorpi,

i have installed the demo but can´t get it working.
Mqtt and ESP32 working correctly, but the Dashboard won´t.
Getting following error:
`Line 91:  'mqtt' is assigned a value but never used  no-unused-vars
`
I have installed npm install mqtt but it dose't help.

**Comment by jarkko-hautakorpi** [comment]
Fixed ESLint warning/error about unused variable.
https://github.com/jarkko-hautakorpi/iBeacon-indoor-positioning-demo/commit/10a22d9427e63cdf199e63d87789e0770ee3ac6c
