### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rishaldyprisly** [jarkko-hautakorpi/iBeacon-indoor-positioning-demo#3]
` 25 | if(msg !== null) {
> 26 |     for(let i=0; i<msg.e.length;i++) {                               <--------
  27 |         let mac = msg.e[i].m.toLowerCase();
  28 |         let station = msg.st.toLowerCase();
  29 |         if(this.stations.includes(station)) {`

Thankyou for created this great project, i need some help in here.

**Comment by jarkko-hautakorpi** [comment]
Did you modify the ESP32 code? The "e" is the SenML object (JSON) message which the ESP32 is sending. Try starting Mosquitto in verbose debug mode to see if you receive valid data:
`mosquitto -v -c mosquitto.conf`
